In [7]:
import pandas as pd
import os

print("Files in raw folder:", os.listdir('../data/raw/'))

movies = pd.read_csv('../data/raw/movies.csv')
ratings = pd.read_csv('../data/raw/ratings.csv')

print("\n--- Movies Data ---")
display(movies.head())

print("\n--- Ratings Data ---")
display(ratings.head())

Files in raw folder: ['movies.csv', 'ratings.csv']

--- Movies Data ---

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

--- Ratings Data ---

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [8]:
# 1. نشوفو معلومات الداتا (واش كاين قيم فارغة NaN)
print("--- Movies Info ---")
movies.info()

print("\n--- Ratings Info ---")
ratings.info()

# 2. نحسبو شحال من قيمة فارغة في كل عمود
print("\n--- Missing Values in Movies ---")
print(movies.isnull().sum())

print("\n--- Missing Values in Ratings ---")
print(ratings.isnull().sum())

--- Movies Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10329 entries, 0 to 10328
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  10329 non-null  int64
 1   title    10329 non-null  object
 2   genres   10329 non-null  object
dtypes: int64(1), object(2)
memory usage: 242.2+ KB

--- Ratings Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105339 entries, 0 to 105338
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     105339 non-null  int64
 1   movieId    105339 non-null  int64
 2   rating     105339 non-null  float64
 3   timestamp  105339 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.2 MB

--- Missing Values in Movies ---
movieId    0
title      0
genres     0
dtype: int64

--- Missing Values in Ratings ---
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [9]:
# ==========================================
# 2. INITIAL EXPLORATION
# ==========================================
print("--- Movies Info ---")
movies.info()

print("\n--- Ratings Info ---")
ratings.info()

print("\n--- Missing Values ---")
print("Movies missing:\n", movies.isnull().sum())
print("Ratings missing:\n", ratings.isnull().sum())

# شوفو أول 5 أسطر
display(movies.head())
display(ratings.head())

--- Movies Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10329 entries, 0 to 10328
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  10329 non-null  int64
 1   title    10329 non-null  object
 2   genres   10329 non-null  object
dtypes: int64(1), object(2)
memory usage: 242.2+ KB

--- Ratings Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105339 entries, 0 to 105338
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     105339 non-null  int64
 1   movieId    105339 non-null  int64
 2   rating     105339 non-null  float64
 3   timestamp  105339 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.2 MB

--- Missing Values ---
Movies missing:
 movieId    0
title      0
genres     0
dtype: int64
Ratings missing:
 userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [10]:
# ==========================================
# 3. CLEANING MOVIES DATASET
# ==========================================
# 1. نحيدو أي سطر ما فيهش عنوان الفيلم (إذا كاين)
movies.dropna(subset=['title'], inplace=True)

# 2. نستخرجو الـ Genres (Action, Comedy...) ونحولوهم لأعمدة (0 و 1)
# نستعملو الدالة explode() باش نفصلو التصنيفات
genres_dummies = movies['genres'].str.get_dummies(sep='|')

# ندمجو الداتا الأصلية مع التصنيفات الجديدة
movies_cleaned = pd.concat([movies, genres_dummies], axis=1)

# 3. نحيدو العمود القديم 'genres' حيت ولى مقسم
movies_cleaned.drop(columns=['genres'], inplace=True)

print(f"Movies cleaned. New shape: {movies_cleaned.shape}")
display(movies_cleaned.head())

Movies cleaned. New shape: (10329, 22)

,movieId,title,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
# ==========================================
# 4. CLEANING RATINGS DATASET
# ==========================================
# 1. نشوفو توزيع التقييمات (من 0.5 لـ 5.0)
print("Rating values distribution:")
print(ratings['rating'].value_counts().sort_index())

# 2. نتأكدو بلي ما كاينش تقييمات سالبة ولا أكبر من 5
ratings = ratings[(ratings['rating'] >= 0.5) & (ratings['rating'] <= 5.0)]

# 3. نشوفو واش كاين تكرارات (نفس المستخدم قيم نفس الفيلم مرتين)
duplicates = ratings.duplicated(subset=['userId', 'movieId']).sum()
print(f"\nNumber of duplicate ratings: {duplicates}")

if duplicates > 0:
    ratings.drop_duplicates(subset=['userId', 'movieId'], keep='last', inplace=True)
    print("Duplicates removed.")

print(f"Ratings cleaned. New shape: {ratings.shape}")

Rating values distribution:
rating
0.5     1198
1.0     3258
1.5     1567
2.0     7943
2.5     5484
3.0    21729
3.5    12237
4.0    28880
4.5     8187
5.0    14856
Name: count, dtype: int64

Number of duplicate ratings: 0
Ratings cleaned. New shape: (105339, 4)

In [12]:
# ==========================================
# 5. FILTERING SPARSE DATA (Very Important for RecSys)
# ==========================================
# 1. نحيدو الأفلام اللي عندها أقل من 10 تقييمات
movie_counts = ratings['movieId'].value_counts()
popular_movies = movie_counts[movie_counts >= 10].index
ratings_filtered = ratings[ratings['movieId'].isin(popular_movies)]

# 2. نحيدو المستخدمين اللي قيمو أقل من 5 أفلام
user_counts = ratings_filtered['userId'].value_counts()
active_users = user_counts[user_counts >= 5].index
ratings_filtered = ratings_filtered[ratings_filtered['userId'].isin(active_users)]

print(f"Original ratings: {ratings.shape[0]}")
print(f"Filtered ratings: {ratings_filtered.shape[0]}")
print(f"Remaining Users: {ratings_filtered['userId'].nunique()}")
print(f"Remaining Movies: {ratings_filtered['movieId'].nunique()}")

Original ratings: 105339
Filtered ratings: 84049
Remaining Users: 668
Remaining Movies: 2315

In [13]:
# ==========================================
# 6. MERGE & SAVE PROCESSED DATA
# ==========================================
# ندمجو الأفلام مع التقييمات
final_dataset = pd.merge(ratings_filtered, movies_cleaned, on='movieId', how='inner')

print(f"Final Merged Dataset Shape: {final_dataset.shape}")
display(final_dataset.head())

# نحفظو الملفات في فولدر processed
PROCESSED_PATH = '../data/processed/'
os.makedirs(PROCESSED_PATH, exist_ok=True) # نتأكدو بلي الفولدر كاين

movies_cleaned.to_csv(PROCESSED_PATH + 'cleaned_movies.csv', index=False)
ratings_filtered.to_csv(PROCESSED_PATH + 'cleaned_ratings.csv', index=False)
final_dataset.to_csv(PROCESSED_PATH + 'final_dataset.csv', index=False)

print("\n✅ Data Cleaning Complete! Files saved to data/processed/")

Final Merged Dataset Shape: (84049, 25)

,userId,movieId,rating,timestamp,title,(no genres listed),Action,Adventure,Animation,Children,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,16,4.0,1217897793,Casino (1995),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,24,1.5,1217895807,Powder (1995),0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1,32,4.0,1217896246,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),0,0,0,0,0,...,0,0,0,0,1,0,1,1,0,0
3,1,47,4.0,1217896556,Seven (a.k.a. Se7en) (1995),0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
4,1,50,4.0,1217896523,"Usual Suspects, The (1995)",0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

✅ Data Cleaning Complete! Files saved to data/processed/